<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CreditFund extends Model
{
    use HasFactory;
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
//            $model->trx_id = CreditFund::where('trx_id',$model->trx_id)->max('id')+1;
//            $model->trx_id = 'trx-'.str_pad($model->trx_id,5,'0', STR_PAD_LEFT);
        });
    }


    public function fundFrom()
    {
        return $this->belongsTo(Fund::class,'from_id', 'id');
    }
    public function fundTo()
    {
        return $this->belongsTo(Fund::class,'to_id', 'id');
    }



}
